### ISSUE TITLE
Can write stream to console window, but not to Serlilog Log !

### ISSUE THREAD

**Issue by mrafea** [VQComms/TracingMiddleware#2]
The TracingMiddleware is working fine console window.
if  try to log -using Serilog- , TracingMiddleware is working fine expect for streams!
The   modifications are :
on class " internal class TracingMiddlewareOptionsTracer : ITracer" :
on "public void Trace(string key, object value)"
After  "  options.Trace(options.MessageFormat(key, typeFormat(value)));"
  i added
  Serilog.Log.Information("Owin key_value on {key} , value  {value}", key, typeFormat(value));

on testing :
when it come to = "owin.RequestBody"
console  window output the stream.
Serlilog  receive empty stream !

Could you please guide me       , i need to log the request stream ?

**Comment by jchannon** [comment]
I've not used Serilog. The console doesnt log the incoming stream if I remember rightly it just says `owin.RequestBody : [Stream]` or something similar.

**Comment by mrafea** [comment]
:100: It works perfectly .
Also  The console log the incoming stream.
the issue was : "When we read from the HttpContent, we read from a stream, once we read from it, it is consumed ,meaning that it can’t be read again".
i had just committed the line :" options.Trace(options.MessageFormat(key, typeFormat(value)));"
and added :
 if (key != "owin.RequestBody")
            {
                Serilog.Log.Information("pair key_value on {key} , value  {value}", key, typeFormat(value));
            }
            else
            {
               StringReader textReader = new StringReader(typeFormat(value));
               string requestData = (textReader.ReadToEnd());
             Serilog.Log.Information("Owin key_value on {key} , value  {value}", key, requestData);
            }

Thanks for the code.
